name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.11, 3.8, 3.9 ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: "8.0"
          mysql database: "simple_django_auth_db"
          mysql port: 3306
          host port: 3306
          mysql user: "python"
          mysql password: "python123"
          mysql root password: "password"  # ここは適当なパスワードに変更してください
      - name: Set up
        env:
          ENGINE: django.db.backends.mysql
          NAME: simple_django_auth_db
          USER: python
          PASSWORD: python123
          HOST: 127.0.0.1
          PORT: 3306
        run: |
          echo "CREATE USER '$USER'@'$HOST' IDENTIFIED BY '$PASSWORD';" | mysql -h $HOST -P $PORT -uroot -p"$MYSQL_ROOT_PASSWORD"
          echo "GRANT ALL ON $NAME.* TO '$USER'@'$HOST';" | mysql -h $HOST -P $PORT -uroot -p"$MYSQL_ROOT_PASSWORD"
          python3 --version
          python3 -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python manage.py makemigrations hello
          
          # Output the environment variables
          echo $ENGINE
          echo $NAME
          echo $USER
          echo $PASSWORD
          echo $HOST
          echo $PORT
          
          python manage.py migrate
          python manage.py test
