name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.11, 3.8, 3.9 ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup MySQL
        uses: Mirantis/mysql-action@v1.0
        with:
          host port: 3306
          container port: 3306
          mysql version: '8.0'
          mysql database: 'simple_django_auth_db'
          mysql root password: 'password'
      - name: Set up
        env:
          ENGINE: django.db.backends.mysql
          NAME: simple_django_auth_db
          USER: root
          PASSWORD: password
          HOST: 127.0.0.1
          PORT: 3306
        run: |
          echo "CREATE USER '$USER'@'$HOST' IDENTIFIED WITH mysql_native_password BY '$PASSWORD';" | mysql -h $HOST -P $PORT -uroot -p"$PASSWORD"
          echo "GRANT ALL ON $NAME.* TO '$USER'@'$HOST';" | mysql -h $HOST -P $PORT -uroot -p"$PASSWORD"
          python3 --version
          python3 -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python manage.py makemigrations hello
          
          # Output the environment variables
          echo $ENGINE
          echo $NAME
          echo $USER
          echo $PASSWORD
          echo $HOST
          echo $PORT
          
          python manage.py migrate
          python manage.py test